### ISSUE TITLE
The Linux Download button stopped working

### ISSUE THREAD

**Issue by Lore-Soong** [LaserFlash/steam-chat-skin-website#1228]
as stated in title i can no longer produce a webkit.css

**Comment by LaserFlash** [comment]
Thanks for bringing this to my attention.

I will investigate over the weekend, and update this when I have a fix.

**Comment by LaserFlash** [comment]
Bug resolved with ba98b38

Fix deployed to https://chat.lasr.skin

@Lore-Soong let me know if you continue to have problems
